### PR TITLE
add flag for .env format

### PR DESCRIPTION
**Pull request by sethpollack**

### CODE REVIEW

**Comment by danenania** [comment]
Thanks @sethpollack! This looks good--would you mind adding a test case here: https://github.com/envkey/envkey-source/blob/master/shell/shell_test/shell_test.go

**Comment by sethpollack** [comment]
@danenania done!

**Comment by danenania** [comment]
@sethpollack thanks! just merged/released in 1.2.5

**Comment by sethpollack** [comment]
Thanks!

**Pull request merged**
