### PR TITLE
don't add extra quote's

### PR DESCRIPTION
**Pull request by sethpollack**

### CODE REVIEW

**Comment by sethpollack** [comment]
@danenania can you take a look at this PR?

**Comment by danenania** [comment]
@sethpollack Do the quotes cause an issue for you? My preference would be to leave them if not to avoid edge cases wrt spacing/other characters.

**Comment by Rizbe** [comment]
Ran into an issue with this, when pulling down the secrets and encoding to base64 for K8s secret, the double quotes causes the quotes to be added to the actual secret when decoding to base64. 

Happy to add an extra step to strip out the double quotes if you guys prefer to keep ""

**Comment by danenania** [comment]
Perhaps a top-level `--omit-quotes` flag could make sense for those scenarios, though I'm a bit wary of setting up shell injection tripwires if the output later gets eval'd in some way .

**Comment by sethpollack** [comment]
I'm just going to pipe through xargs:
```
 envkey-source --dot-env-compatible | xargs printf "%s\n"
```

**Comment by danenania** [comment]
@sethpollack That looks good. Given how simple it is I like leaving quotes as a safe default and then leaving it up to more advanced users to strip them out where appropriate.

**Pull request closed without merging**
